name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Are you sure you want to destroy the infrastructure?'
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: apply
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_USE_OIDC: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Init
      run: terraform -chdir=terraform/ init

    - name: Terraform Plan (destroy)
      run: terraform -chdir=terraform/ plan -destroy -input=false
      env:
        TF_VAR_admin_username: ${{secrets.TF_VAR_ADMIN_USERNAME}}
        TF_VAR_admin_password: ${{secrets.TF_VAR_ADMIN_PASSWORD}}
        TF_VAR_admin_ssh_public_key: ${{secrets.TF_VAR_ADMIN_SSH_PUBLIC_KEY}}

    - name: Terraform Destroy
      if: github.event.inputs.confirm_destroy == 'true'
      run: terraform -chdir=terraform/ destroy -auto-approve
      env:
        TF_VAR_admin_username: ${{secrets.TF_VAR_ADMIN_USERNAME}}
        TF_VAR_admin_password: ${{secrets.TF_VAR_ADMIN_PASSWORD}}
        TF_VAR_admin_ssh_public_key: ${{secrets.TF_VAR_ADMIN_SSH_PUBLIC_KEY}}
