name: Manual - Terraform Plan / Apply

on:
  workflow_dispatch:
    inputs:
      action_type:
        type: boolean
        description: Should terraform apply be run?
        required: true
        default: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
    plan_apply:
      runs-on: ubuntu-latest
      environment: apply
      env:
        ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
        ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Azure CLI Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Install terraform
          uses: hashicorp/setup-terraform@v1

        - name: Download terraform dependencies
          run: terraform -chdir=terraform/ init
            
        - name: Terraform Plan
          run: terraform -chdir=terraform/ plan -input=false
        
        - name: Terraform Apply
          if: github.event.inputs.action_type
          run: terraform -chdir=terraform/ apply -auto-approve  
